// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVFGtBAXxPRZYSDFPNCNd8ZA4LR08QUrU',
    appId: '1:1089975698754:web:b3455c56a50db22c9fb4db',
    messagingSenderId: '1089975698754',
    projectId: 'meetie-a-meeting-app',
    authDomain: 'meetie-a-meeting-app.firebaseapp.com',
    storageBucket: 'meetie-a-meeting-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuOK7dtsjHc0BdbabDWb2gPQ3myPrbA6I',
    appId: '1:1089975698754:android:1397dd8e1968089b9fb4db',
    messagingSenderId: '1089975698754',
    projectId: 'meetie-a-meeting-app',
    storageBucket: 'meetie-a-meeting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8dAW6iNip6TF4DHpwZpChUVh__3goMbQ',
    appId: '1:1089975698754:ios:e46470de0c5a3afd9fb4db',
    messagingSenderId: '1089975698754',
    projectId: 'meetie-a-meeting-app',
    storageBucket: 'meetie-a-meeting-app.appspot.com',
    iosBundleId: 'com.example.meetie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8dAW6iNip6TF4DHpwZpChUVh__3goMbQ',
    appId: '1:1089975698754:ios:e46470de0c5a3afd9fb4db',
    messagingSenderId: '1089975698754',
    projectId: 'meetie-a-meeting-app',
    storageBucket: 'meetie-a-meeting-app.appspot.com',
    iosBundleId: 'com.example.meetie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVFGtBAXxPRZYSDFPNCNd8ZA4LR08QUrU',
    appId: '1:1089975698754:web:8e15a81620ec8f079fb4db',
    messagingSenderId: '1089975698754',
    projectId: 'meetie-a-meeting-app',
    authDomain: 'meetie-a-meeting-app.firebaseapp.com',
    storageBucket: 'meetie-a-meeting-app.appspot.com',
  );

}